[package]
name = "hubris-task-slots"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
userlib.workspace = true

[lib]
test = false
bench = false
doctest = false

[build-dependencies]
ron = "0.8.1"
