[package]
name = "openprot-platform-aspeed"
version = "0.1.0"
edition = "2021"
description = "OpenPRoT platform implementation for Aspeed AST1060"
license = "Apache-2.0"

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
panic-halt = { workspace = true }
zerocopy = { workspace = true }
ast1060-pac = { workspace = true }
openprot-hal-blocking = { path = "../../../../hal/blocking" }
