# Licensed under the Apache-2.0 license
# SPDX-License-Identifier: Apache-2.0

load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "pldm_gate",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//services/orchestrator/config:orchestrator_config",
        "//services/pldm/api:pldm_api",
    ],
)

rust_test(
    name = "pldm_gate_test",
    crate = ":pldm_gate",
)
