[package]
name = "idle"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib = {workspace = true, features = ["no-panic"]}

[features]
insomniac = []

[[bin]]
name = "idle"
test = false
bench = false
