# Licensed under the Apache-2.0 license
# SPDX-License-Identifier: Apache-2.0

load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "pldm_server",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//services/pldm/api:pldm_api",
        "//util/service",
    ],
)

rust_test(
    name = "pldm_server_test",
    crate = ":pldm_server",
)
