[package]
edition = "2021"
readme = "README.md"
name = "ast1060-starter"
version = "0.1.0"

[features]
jtag-halt = []

[dependencies]
# TODO: Add these when we have full ExHubris workspace setup
# userlib = { workspace = true }
# hubris-notifications = { workspace = true } 
# hubris-task-slots = { workspace = true }

# For now, just minimal dependencies for standalone build
cortex-m = "0.7.7"

# this lets you use `cargo fix`!
[[bin]]
name = "ast1060-starter"
test = false
doctest = false
bench = false
